### ISSUE TITLE
[Bug] Consistently pass configuration to TM and OMS noise generation

### ISSUE THREAD

**Issue by james-alvey-42** [Mauropieroni/GW_response#7]
**Description**
At the moment, the way that the time configuration axis is passed in `single_link_TM_acceleration_noise_variance` and `single_link_OMS_noise_variance` is not consistent, since `single_link_OMS_noise_variance` does not do anything with the `arms_matrix_rescaled` argument (which contains the configuration axis).

This does get fixed when passed through the TDI in `tdi_projection` which takes `arms_matrix_rescaled` as input, but would be good to be consistent across the functions.

**Fixes**
Either insist that the parameters for `TM_acceleration_parameters` and `OMS_parameters` must have shape `[time, 6]` rather than just `6`, or pass directly the configuration axis within `single_link_OMS_noise_variance`.

**Comment by Mauropieroni** [comment]
Added a test to check shapes
